apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ template "flink-job-cluster.fullname" . }}
  labels:
    app: {{ template "flink-job-cluster.name" . }}
    chart: {{ template "flink-job-cluster.chart" . }}
    release: {{ .Release.Name }}
data:
  config.properties: |
    {{- .Values.taskManager.config.properties | nindent 4 }}
